version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}  # Use environment variable from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Use environment variable from .env
      POSTGRES_DB: ${DB_NAME}  # Use environment variable from .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db  # Reference the db service
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

volumes:
  pgdata:
